FROM node:18

# COPY BoozeOrNo/frontend/package.json ./package.json
# COPY BoozeOrNo/frontend/package-lock.json ./package-lock.json
COPY frontend frontend
WORKDIR BoozeOrNo/frontend

RUN npm install

CMD ["npm", "start"]
